"""Rebake, rebuild and install every asset, in one command.

    hython scripts/rebuild_assets.py            # and install for every local Houdini
    hython scripts/rebuild_assets.py --no-install

Why one command. An asset and the ``rpfarm`` package are one product in two
files, and keeping them together used to take four steps done by hand: bake
the fingerprint, rebuild the two generated HDAs, expand them back into the
repository, install all four into Houdini. ``tests/test_hda_assets.py``
guards the first three -- it fails when the checkout's assets drift from the
package. It cannot see the fourth, because the copy an artist cooks with
lives in their preferences directory, not in the repository.

On 2026-09-07 that gap cost a day: the assets were rebuilt in the checkout,
the tests were green, and the artist went on cooking with the build from the
day before, because "rebuilt" and "installed" were two separate steps and
only the first one ran. This script makes them one step, and
``rpfarm doctor`` now reads the fingerprint baked into the INSTALLED file so
the gap is also *detectable* from the artist's side.

Needs hython: the two generated HDAs are built by scripts that create real
nodes.
"""

from __future__ import annotations

import argparse
import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
if str(REPO) not in sys.path:
    sys.path.insert(0, str(REPO))

#: The assets that are GENERATED by a builder script. Only the scheduler is
#: hand-edited in the repository; it needs rebaking, which the bake script
#: does in place. Leaving one of these out is the same class of bug this
#: whole script exists to kill -- tests/test_hda_assets.py's BUILDERS map is
#: the authority, and a test asserts these two agree.
GENERATED = {
    "runpodfarm_upload": "build_runpodfarm_upload_hda.py",
    "runpodfarm_download": "build_runpodfarm_download_hda.py",
    "runpodfarm_stats": "build_runpodfarm_stats_hda.py",
}


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def rebake():
    """Rewrite every baked fingerprint block. Returns the files it changed."""
    bake = _load("bake_asset_fingerprint", REPO / "scripts" / "bake_asset_fingerprint.py")
    guard = bake._hda_guard()
    block = bake.current_block(guard)
    return [p for p in bake.TARGETS if bake.rewrite(p, guard, block)]


def rebuild_generated(hotl: Path, log=print):
    """Run each builder and expand its output back into ``hda/``."""
    built = []
    with tempfile.TemporaryDirectory(prefix="rpfarm-assets-") as tmp:
        for name, builder in sorted(GENERATED.items()):
            out = Path(tmp) / f"{name}.hda"
            proc = subprocess.run(
                [sys.executable, str(REPO / "scripts" / builder), str(out)],
                capture_output=True, text=True)
            if proc.returncode != 0 or not out.exists():
                raise SystemExit(
                    f"{builder} failed (exit {proc.returncode}):\n"
                    f"{proc.stdout}\n{proc.stderr}")
            target = REPO / "hda" / f"{name}.hda"
            # hotl -t refuses to write into a directory that already has a
            # different asset in it, so the old expansion goes first. This is
            # the same two-step the builders' own docstrings prescribe.
            if target.exists():
                shutil.rmtree(target)
            subprocess.run([str(hotl), "-t", str(target), str(out)], check=True)
            log(f"rebuilt {target.relative_to(REPO)}")
            built.append(name)
    return built


def _unpin_pref_dir():
    """Stop hython's own HOUDINI_USER_PREF_DIR standing in for every version.

    hython exports the RUNNING Houdini's preference directory. HoudiniInstall
    honours that variable (deliberately -- see its docstring), so under
    hython every installed Houdini resolves to the 22.0 prefs and a machine
    with two versions gets the assets installed twice into one of them and
    never into the other.

    Houdini documents ``__HVER__`` for exactly this, so the fix is to put it
    back: when the variable ends in the running version's ``major.minor``,
    that segment is hython's doing, and replacing it with the placeholder
    keeps a relocated prefs ROOT (which would be the artist's own choice)
    while letting each install pick its own version directory.
    """
    import os

    import hou

    current = os.environ.get("HOUDINI_USER_PREF_DIR")
    if not current:
        return
    version = ".".join(hou.applicationVersionString().split(".")[:2])
    head, sep, tail = current.rstrip("/").rpartition("/")
    if sep and tail == version:
        os.environ["HOUDINI_USER_PREF_DIR"] = head + "/__HVER__"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--no-install", action="store_true",
                        help="rebake and rebuild, but do not touch any Houdini prefs")
    args = parser.parse_args(argv)

    try:
        import hou  # noqa: F401
    except ImportError:
        raise SystemExit(
            "this needs hython -- the generated assets are built by creating "
            "real nodes. Run it as `hython scripts/rebuild_assets.py`.")

    import rpfarm
    from rpfarm import houdini_local

    _unpin_pref_dir()
    installs = houdini_local.find_houdini_installations()
    if not installs:
        raise SystemExit("no local Houdini installation found -- nothing to build with")
    hotl = installs[0].hotl
    if hotl is None:
        raise SystemExit(f"hotl not found next to {installs[0].hython}")

    changed = rebake()
    for path in changed:
        print(f"rebaked {path.relative_to(REPO)}")
    if not changed:
        print("fingerprints already current")
    rebuild_generated(hotl)

    if args.no_install:
        print("not installing (--no-install); assets in hda/ are current")
        return 0

    cache = Path.home() / ".rpfarm" / "otls"
    cache.mkdir(parents=True, exist_ok=True)
    fingerprint = rpfarm.fingerprint()
    failures = 0
    for install in installs:
        results = houdini_local.build_and_install_hdas(install, cache)
        bad = [r for r in results if not r["ok"]]
        for r in bad:
            print(f"  FAILED {r['name']}: {r['error']}")
        houdini_local.install_node_shape(install)
        houdini_local.install_shelf_tool(install)
        houdini_local.write_rpfarm_root_env(install)

        # The point of the whole script: prove the installed copy agrees with
        # the package, rather than assuming the copy step did what it said.
        states = houdini_local.installed_asset_states(install, fingerprint)
        stale = [n for n, st in states.items() if st["stale"]]
        missing = [n for n, st in states.items() if not st["present"]]
        if bad or stale or missing:
            failures += 1
            print(f"[FAIL] Houdini {install.version}: "
                  f"{len(bad)} failed, {len(stale)} stale ({', '.join(stale)}), "
                  f"{len(missing)} missing")
        else:
            print(f"[OK] Houdini {install.version}: 4/4 installed and matching "
                  f"({install.user_pref_dir / 'otls'})")
    if failures:
        return 1
    print("Restart Houdini (or File > Reload Assets) to pick the new definitions up.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
